-- 更新 TaskCategory 枚举，添加新值
ALTER TYPE "TaskCategory" ADD VALUE IF NOT EXISTS 'SPECIAL';
ALTER TYPE "TaskCategory" ADD VALUE IF NOT EXISTS 'CHALLENGE';
ALTER TYPE "TaskCategory" ADD VALUE IF NOT EXISTS 'PK';
ALTER TYPE "TaskCategory" ADD VALUE IF NOT EXISTS 'HABIT';

-- 更新 TaskType 枚举，添加新值
ALTER TYPE "TaskType" ADD VALUE IF NOT EXISTS 'BADGE';
ALTER TYPE "TaskType" ADD VALUE IF NOT EXISTS 'PK';
ALTER TYPE "TaskType" ADD VALUE IF NOT EXISTS 'PK_RESULT';
ALTER TYPE "TaskType" ADD VALUE IF NOT EXISTS 'HABIT';
